// static int run_face_recognition(fb_data_t *fb, std::list<dl::detect::result_t> *results)
// static esp_err_t bmp_handler(httpd_req_t *req)
// static size_t jpg_encode_stream(void *arg, size_t index, const void *data, size_t len)
// static esp_err_t capture_handler(httpd_req_t *req)
// static esp_err_t stream_handler(httpd_req_t *req)
// void startCameraServer()
